<?php

/**
 * @file
 * Contains custom_graphql.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_graphql_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.custom_graphql':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides custom GraphQL schema extensions for paragraphs.') . '</p>';
      return $output;
    default:
  }
} 